### ISSUE TITLE
Need help about HDMI output

### ISSUE THREAD

**Issue by trankimlonghai** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#14]
Hi, first things first, sorry about the off-topic... I've removed it already.
Okay, let's step right in:
Base on your working CLOVER for models Rog strix, surprisingly, yes, my model G531GU also seems work fine. But there's still thing need to be done. More specific:

Your CLOVER works also already be patched HDMI output or not ? If not, then is there a guide... easily to understand to patch it (with Hackintool) ? :''D

**Comment by trankimlonghai** [comment]
@williambj1 wi
hi, can you help me out with HDMI issue ?

**Comment by trankimlonghai** [comment]
@williambj1 
I read somewhere randomly on the internet and they said there's some laptop (like rog strix, mine i am using) HDMI output just use discret graphics, not on-board GPU (Intel) so no hope for patching HDMI output, is this true or not ? How about your HDMI output ?

**Comment by williambj1** [comment]
As far as I know, **ALL** Asus gaming laptops have HDMI connected to NVIDIA's graphics card. And unfortunately, it's impossible to get those graphics cards to work properly in macOS.

This issue is already discussed in #10 & #11,  closed as duplication. If you have more questions consider opening a dedicated issue.

---

> Base on your working CLOVER for models Rog strix

It's **Zephyrus**, actually. Asus uses almost the same motherboard on every gaming laptop.
